---
- name: users | check if group name is defined
  ansible.builtin.assert:
    that:
      - item.name is defined
    quiet: true
    fail_msg: Group name must be defined
  loop: "{{ users_groups }}"

- name: users | check if user name is defined
  ansible.builtin.assert:
    that:
      - item.name is defined
    quiet: true
    fail_msg: User name must be defined
  loop: "{{ users_users }}"

- name: users | check update_password option
  ansible.builtin.assert:
    that:
      - item.update_password in ['always', 'on_create']
    quiet: true
    fail_msg: The update_password option must be 'always' or 'on_create'
  loop: "{{ users_users }}"
  when: item.update_password is defined
