- name: delete | get a lists of users and groups to delete
  ansible.builtin.set_fact:
    __groups_to_delete: "{{ ansible_local.users.managed_groups | difference(users_groups | map(attribute='name')) }}"
    __users_to_delete: "{{ ansible_local.users.managed_users | difference(users_users | map(attribute='name')) }}"
  when: ansible_local.users is defined

- name: delete | remove users
  ansible.builtin.user:
    state: absent
    name: "{{ item }}"
    force: "{{ users_remove_force }}"
    remove: "{{ users_remove_home }}"
  loop: "{{ __users_to_delete }}"
  when:
    - ansible_local.users.managed_users is defined
    - ansible_local.users.managed_users | length > 0

- name: delete | remove groups
  ansible.builtin.group:
    state: absent
    name: "{{ item }}"
    force: "{{ users_remove_force }}"
  loop: "{{ __groups_to_delete }}"
  when:
    - ansible_local.users.managed_groups is defined
    - ansible_local.users.managed_groups | length > 0
