- name: facts | ensure ansible custom fact directory existed
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: facts | template users fact file
  ansible.builtin.template:
    src: users.fact.j2
    dest: /etc/ansible/facts.d/users.fact
    owner: root
    group: root
    mode: "0644"
