name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish on Ansible Galaxy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release Ansible Role to Galaxy
        uses: hspaans/ansible-galaxy-action@v2.0.0
        with:
          api_key: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
